### ISSUE TITLE
Clean build fails  Non-resolvable parent POM: Could not find artifact com.arcbees:gwtchosen-project:pom:2.0.1-SNAPSHOT

### ISSUE THREAD

**Issue by komasoftware** [ArcBees/gwtchosen#229]
cloned the repo, starting maven :

```
koen@desktop:~/workspace/gwtchosen$ ll
total 64
drwxrwxr-x  7 koen koen  4096 Mai 27 15:16 ./
drwxrwxr-x 10 koen koen  4096 Mai 27 15:16 ../
-rw-rw-r--  1 koen koen   866 Mai 27 15:16 assembly.xml
drwxrwxr-x  8 koen koen  4096 Mai 27 15:16 .git/
-rw-rw-r--  1 koen koen   440 Mai 27 15:16 .gitattributes
-rw-rw-r--  1 koen koen   102 Mai 27 15:16 .gitconfig
-rw-rw-r--  1 koen koen   734 Mai 27 15:16 .gitignore
drwxrwxr-x  3 koen koen  4096 Mai 27 15:16 integration-test/
-rw-rw-r--  1 koen koen   549 Mai 27 15:16 LICENSE
drwxrwxr-x  3 koen koen  4096 Mai 27 15:16 plugin/
-rw-rw-r--  1 koen koen 11826 Mai 27 15:16 pom.xml
-rw-rw-r--  1 koen koen  2842 Mai 27 15:16 README.md
drwxrwxr-x  2 koen koen  4096 Mai 27 15:16 release/
drwxrwxr-x  3 koen koen  4096 Mai 27 15:16 sample/
koen@desktop:~/workspace/gwtchosen$ mvn
[INFO] Scanning for projects...
[ERROR] The build could not read 3 projects -> [Help 1]
[ERROR]   
[ERROR]   The project com.arcbees:gwtchosen:2.0.1-SNAPSHOT (/home/koen/workspace/gwtchosen/plugin/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM: Could not find artifact com.arcbees:gwtchosen-project:pom:2.0.1-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 5, column 13 -> [Help 2]
[ERROR]   
[ERROR]   The project com.arcbees:integration-test:2.0.1-SNAPSHOT (/home/koen/workspace/gwtchosen/integration-test/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM: Could not find artifact com.arcbees:gwtchosen-project:pom:2.0.1-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 5, column 13 -> [Help 2]
[ERROR]   
[ERROR]   The project com.arcbees:chosen-sample:2.0.1-SNAPSHOT (/home/koen/workspace/gwtchosen/sample/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM: Could not find artifact com.arcbees:gwtchosen-project:pom:2.0.1-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 5, column 13 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
koen@desktop:~/workspace/gwtchosen$ 
```

**Comment by komasoftware** [comment]
I have fixed this locally by bringing the version of the child poms inline with the version of the pom in the root of the project.

**Comment by olafleur** [comment]
We fixed the problem with the parent POM in the new snapshot (version 2.0.2-SNAPSHOT). If that's not the case, please reopen.

**Comment by emishas** [comment]
hm, still seeing same issue..

did the same thing as @komasoftware, but vice versa - brought the version of the root pom inline with the child poms and:
```
[INFO] Reactor Summary:
[INFO] 
[INFO] gwtchosen-project ................................. SUCCESS [02:12 min]
[INFO] gwtchosen ......................................... SUCCESS [ 40.753 s]
[INFO] integration-test .................................. SUCCESS [ 28.027 s]
[INFO] chosen-sample ..................................... SUCCESS [01:45 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 05:07 min
[INFO] Finished at: 2015-07-13T14:55:28+09:00
[INFO] Final Memory: 49M/486M
[INFO] ------------------------------------------------------------------------
```
